/*global module */
module.exports = function (grunt) {

    "use strict";

    // Project configuration.
    grunt.initConfig({

        pkg: grunt.file.readJSON('package.json'),

        uglify: {
            options: {
                banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd hh:mm") %> */\n'
            },
            build: {
                src: 'src/<%= pkg.name %>.js',
                dest: 'build/<%= pkg.name %>.min.js'
            }
        },

        copy: {
            main: {
                expand: true,
                cwd: 'src',
                src: ['**'],
                dest: '../jemanitori-theme/',
            },
        },

        clean: {
            options: {
                force: true,
            },
            build: {
                src: ['../jemanitori-theme']
            }
        },

        sass: { // Task
            options: { // Target options
                banner: '/*! <%= pkg.name %> theme, generated by Grunt on <%= grunt.template.today("yyyy-mm-dd HH:mm") %> */\n',
                style: 'compact'
            },
            fast: { // Only target important CSS
                files: {
                    '../jemanitori-theme/style.css': 'src/scss/style.scss'
                }
            },
            main: { // Target all files
                files: { // Dictionary of files
                    '../jemanitori-theme/style.css': 'src/scss/style.scss', // 'destination': 'source'
                    '../jemanitori-theme/css/ie.css': 'src/scss/ie.scss',
                    '../jemanitori-theme/css/editor-style.css': 'src/scss/editor-style.scss'
                }
            }
        },

        watch: {
            options: {
                atBegin: true,
                livereload: true
            },
            files: ['**/*.scss'],
            tasks: ['sass:fast'],
        },

        photobox: {
            task: {
                options: {
                    indexPath: 'target/photobox/',
                    screenSizes: ['400', '1200'],
                    urls: ['http://localhost/', 'http://localhost/2014/']
                }
            }
        }

    });

    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-photobox');

    // Default task(s).
    grunt.registerTask('default', ['clean', 'copy']);

};